:rocket: Ci update

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -2,7 +2,10 @@ name: Release
 
 on:
   workflow_dispatch:
-
+  inputs:
+    k3s_base_deps_version:
+      description: 'k3s base image version'
+      required: false
   release:
     types: [created]
 
@@ -109,6 +112,7 @@ jobs:
               tag = ref.replace('refs/heads/release-', '')
               if not re.search('-nightly$', tag):
                   tag += "-nightly"
+                  env_file.write(f"IS_NIGHTLY="YES"\n")
           elif ref.startswith('refs/tags/'):
               tag = ref.replace('refs/tags/', '')
           else:
@@ -136,6 +140,17 @@ jobs:
 
       - uses: actions/checkout@v4
 
+      - name: Set default values
+        id: defaults
+        run: |
+          if [[ "${{ env.IS_NIGHTLY }}" == "YES" && -z "${{ github.event.inputs.k3s_base_deps_version }}" ]]; then
+            echo "Error: k3s_base_deps_version is required for nightly builds."
+            exit 1
+          fi
+
+          IMAGE_NAME=${{ k3s_base_deps_version || steps.tag_name.outputs.TAG_NAME }}
+          echo "image_name=$IMAGE_NAME" >> $GITHUB_ENV
+
       - name: Build & Push Image
         working-directory: ./k3s/k3s-base
         env:
@@ -144,6 +159,8 @@ jobs:
           K3S_VERSION: "v1.31.1+k3s1"
           OVERRIDE_PUSHED_IMAGE: "false"
         run: |
+          IMAGE_TAG=${{ env.image_name }}
+
           set +e
           image_name="ghcr.io/kloudlite/kl/k3s-tacker"
           set -e
